FROM postgres:9.6.6-alpine

RUN echo > /var/lib/postgresql/data/pg_hba.conf  && \
    echo "local all all md5" >> /var/lib/postgresql/data/pg_hba.conf && \
    echo "host all all 127.0.0.1/32 md5" >> /var/lib/postgresql/data/pg_hba.conf && \
    echo "host all all ::1/128 md5" >> /var/lib/postgresql/data/pg_hba.conf && \
    echo "host all all 0.0.0.0/0 md5" >> /var/lib/postgresql/data/pg_hba.conf
