version: '3.3'

services:
  redis:
    container_name: 'redis_backend'
    image: redis
    restart: always
    expose:
      - '6379'

  kitoboy:
    container_name: 'kitoboy'
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - "./env.env"
    ports:
      - "8000:80"

    volumes:
      - './:/var/www/kitoboy/backend'
    depends_on:
      - redis
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile_bd
    container_name: 'kitoboy_db'
    restart: always
    env_file:
      - './postgres_extra/data_base.env'
    ports:
      - "5432:5432"
    volumes:
      - './postgres-data:/var/lib/postgresql/data'
      - './db-logs/:/logs'

volumes:
  postgres-data:
  db-logs:




