"""empty message

Revision ID: 6cd3c025553f
Revises: 
Create Date: 2021-12-07 20:00:23.610306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cd3c025553f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account', sa.Text(), nullable=True),
    sa.Column('socnet_name', sa.Text(), nullable=True),
    sa.Column('is_collected', sa.Boolean(), nullable=True),
    sa.Column('suicide_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_user_socnet_name'), 'user', ['socnet_name'], unique=False)
    op.create_index(op.f('ix_user_user_account'), 'user', ['user_account'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_retweeted', sa.Boolean(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('annotation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_post_text'), 'post', ['text'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_text'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_user_account'), table_name='user')
    op.drop_index(op.f('ix_user_socnet_name'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
