"""empty message

Revision ID: f1a300332cd5
Revises: 
Create Date: 2021-12-19 21:09:17.272370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a300332cd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('from_country', sa.String(), nullable=True),
    sa.Column('study_level', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_volunteer', sa.Boolean(), nullable=True),
    sa.Column('is_supervisor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['real_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('digital_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('associated_real_user', sa.Integer(), nullable=True),
    sa.Column('socnet_id', sa.Text(), nullable=True),
    sa.Column('socnet_name', sa.Text(), nullable=True),
    sa.Column('is_collected', sa.Boolean(), nullable=True),
    sa.Column('account_status', sa.String(), nullable=True),
    sa.Column('last_visited', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['associated_real_user'], ['real_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_digital_user_socnet_id'), 'digital_user', ['socnet_id'], unique=True)
    op.create_index(op.f('ix_digital_user_socnet_name'), 'digital_user', ['socnet_name'], unique=False)
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['real_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('supervised_by',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['real_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['real_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('taken_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('event', sa.DateTime(), nullable=True),
    sa.Column('volunteer_id', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['real_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('volunteered_by',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['real_user.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['real_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('is_retweeted', sa.Boolean(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('annotation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['digital_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_post_text'), 'post', ['text'], unique=False)
    op.create_table('socnet_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_id', sa.Integer(), nullable=True),
    sa.Column('trg_id', sa.Integer(), nullable=True),
    sa.Column('relation_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['src_id'], ['digital_user.id'], ),
    sa.ForeignKeyConstraint(['trg_id'], ['digital_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('socnet_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socnet_id', sa.Integer(), nullable=True),
    sa.Column('model_risk_estimation', sa.String(), nullable=True),
    sa.Column('human_risk_estimation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['socnet_id'], ['digital_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('post_attrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('attr_by_model', sa.String(), nullable=True),
    sa.Column('attr_by_human', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('post_interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['digital_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('post_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_msg_id', sa.Integer(), nullable=True),
    sa.Column('reply_msg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['base_msg_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['reply_msg_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_replies')
    op.drop_table('post_interaction')
    op.drop_table('post_attrs')
    op.drop_table('socnet_risk')
    op.drop_table('socnet_relationship')
    op.drop_index(op.f('ix_post_text'), table_name='post')
    op.drop_table('post')
    op.drop_table('volunteered_by')
    op.drop_table('taken_actions')
    op.drop_table('supervised_by')
    op.drop_table('phone')
    op.drop_index(op.f('ix_digital_user_socnet_name'), table_name='digital_user')
    op.drop_index(op.f('ix_digital_user_socnet_id'), table_name='digital_user')
    op.drop_table('digital_user')
    op.drop_table('address')
    op.drop_table('real_user')
    # ### end Alembic commands ###
